version: '3.8'
services:
    backend: 
        build: ./backend
        ports: 
            - '8000:8000'
        env_file: 
            - ./env/backend.env
    frontend: 
        build: ./frontend
        ports: 
            - '3220:3220'
        env_file: 
            - ./env/frontend.env
        